version: '2'
services:

    mainserver:
     build:
        dockerfile: docker/MainServer/Dockerfile
        context: .
     links:
       - dbserver
     depends_on:
       - dbserver
     ports:
       - "3000:3000"

    dbserver:
     build:
        dockerfile: docker/DBServer/Dockerfile
        context: .
     links:
       - mysql
     depends_on:
       - mysql

    mysql:
      image: mysql:5.7.18
      environment:
        - MYSQL_ROOT_PASSWORD=pass
      volumes:
        - ./build.sql:/tmp/build.sql
        - ./import.sh:/tmp/import.sh
