version: '2'
services:

    mainserver:
     build:
        dockerfile: docker/MainServer/Dockerfile
        context: .
     links:
       - dbserver
     depends_on:
       - dbserver
     ports:
       - "3000:3000"

    dbserver:
     build:
        dockerfile: docker/DBServer/Dockerfile
        context: .
     links:
       - mysql
     depends_on:
       - mysql
     ports:
       - "2999:2999"

    mysql:
      image: mysql:5.7.18
      environment:
       - MYSQL_ROOT_PASSWORD=pass
      command: mysqld --max_allowed_packet=30M
      volumes:
        - ./build.sql:/tmp/build.sql
        - ./import.sh:/tmp/import.sh
      ports:
        - "3306:3306"
